<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- Default to a Console app during Debug mode so you can see logs -->
		<OutputType Condition="'$(Configuration)' == 'Debug'">Exe</OutputType>
		<!-- Change to WinExe in Release mode to hide the black console window -->
		<AllowUnsafeBlocks>enable</AllowUnsafeBlocks>
		<OutputType Condition="'$(Configuration)' == 'Release'">WinExe</OutputType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Raylib-CSharp-Vinculum" Version="5.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Astride.Core\Astride.Core.csproj" />
	</ItemGroup>

</Project>
